In [1]:
import pandas as pd

In [2]:
thor_wwii_data_clean=pd.read_csv("WW2_Missions/data/thor_wwii_data_clean.csv")

thor_wwii_data_clean.head()

/Users/engysamaan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (14,48,49,51,52,59,60) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,wwii_id,master_index_number,msndate,theater,naf,country_flying_mission,tgt_country_code,tgt_country,tgt_location,tgt_type,...,callsign,rounds_ammo,spares_return_ac,wx_fail_ac,mech_fail_ac,misc_fail_ac,target_comment,mission_comments,source,database_edit_comments
0,1,NaN,1943-08-15,MTO,12 AF,USA,13.0,ITALY,SPADAFORA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4285,20028.0,1945-02-20,PTO,5 AF,USA,NaN,PHILIPPINE ISLANDS,PUERTA PRINCESA,UNIDENTIFIED TARGET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,1943-08-15,MTO,12 AF,USA,13.0,ITALY,COSENZA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,1943-08-15,MTO,12 AF,USA,13.0,ITALY,GIOJA TAURO,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
4,8167,14639.0,1945-02-23,PTO,5 AF,USA,NaN,PHILIPPINE ISLANDS,BALETE PASS,WOODED AREA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
thor_wwii_aircraft_gloss=pd.read_csv("WW2_Missions/data/thor_wwii_aircraft_gloss.csv")

thor_wwii_aircraft_gloss.head(10)

,gloss_id,aircraft,name,full_name,aircraft_type,hyperlink
0,1,A20,A20,Douglas A-20 Havoc,Boston Light Bomber / Night-Fighter,http://militaryfactory.com/aircraft/detail.asp...
1,2,A24,A24,Douglass A-24 Banshee,Dive Bomber / Reconnaissance,http://militaryfactory.com/aircraft/detail.asp...
2,3,A26,A26,Douglas A-26 Invader,Medium Bomber / Heavy Assault,http://militaryfactory.com/aircraft/detail.asp...
3,4,A36,A36,North American A-36 Apache (Invader),Ground Attack / Dive Bomber,http://militaryfactory.com/aircraft/detail.asp...
4,5,ALBA,Albacore,Fairey Albacore,Naval Torpedo Bomber,http://militaryfactory.com/aircraft/detail.asp...
5,6,AUDA,Audax,Hawker Audax,Biplane Light Bomber,http://en.wikipedia.org/wiki/Hawker_Hart
6,7,B17,FORT,B-17 Flying Fortress,Heavy Bomber,http://boeing.com/history/products/b-17-flying...
7,8,B24,Liberator,B-24 Liberator,Heavy Bomber,http://militaryfactory.com/aircraft/detail.asp...
8,9,B25,B25,B-25 Mitchell,Medium Bomber,http://militaryfactory.com/aircraft/detail.asp...
9,10,B26,B26,Martin B-26 Marauder,Medium Bomber,http://militaryfactory.com/aircraft/detail.asp...

In [4]:
thor_wwii_weapon_gloss=pd.read_csv("WW2_Missions/data/thor_wwii_weapon_gloss.csv")

thor_wwii_weapon_gloss.head()

,rn,country,weapon_name,weapon_type,weapon_class,number_of_bomblets,alt_weapon_name,weapon_description
0,1,USA,10 lb Incendiary,NaN,IC,NaN,AN-M67 or AN-M69,10 lb Incendiary that used White Phosphorous o...
1,2,USA,100 lb Incendiary,NaN,IC,NaN,M47A2,100 lb M47A2 Incendiary usually loaded with ge...
2,3,USA,100 lb WP (White Phosphrous),NaN,IC,NaN,M47A2,100 lb M47A2 Smoke bomb
3,4,USA,1000 lb aux fuel tank Incendiary,NaN,IC,NaN,NaN,1000 lb Auxiliary fuel tank. When used as ince...
4,5,USA,136 lb (38x4 Clusters) I-M6,I-M6,IC,NaN,M6,M6 Cluster containing 38 AN-M50 incendiary bom...

In [5]:
Summary_of_Weather=pd.read_csv("Weather/Summary_of_Weather.csv")

Summary_of_Weather.head()

FileNotFoundError: File b'Weather/Summary_of_Weather.csv' does not exist

In [ ]:
# selecting the col needed from the Summary_of_Weather DF
Weather =pd.DataFrame(Summary_of_Weather,columns = ["STA", "Date","Precip","WindGustSpd","MaxTemp","MinTemp",
                                                   "MeanTemp", "Snowfall"])
Weather.head()

In [ ]:
# read the Weather_Station_Locations CSV file 
Weather_Station_Locations=pd.read_csv("Weather/Weather_Station_Locations.csv")

Weather_Station_Locations.head()

In [ ]:
# Celening the Weather_Station_Locations DF by droping the unwanted col
weather_station_loc = Weather_Station_Locations.drop(columns=["LAT","LON"])
weather_station_loc.head()

In [ ]:
weather_station_loc['STATE/COUNTRY ID'].unique()

In [ ]:
thor_wwii_weapon_gloss.head()

In [ ]:
# Droping un-needed col from the wepon gloss DF.
weapon_gloss = thor_wwii_weapon_gloss.drop(columns=["weapon_type","weapon_class","number_of_bomblets"])
weapon_gloss.head()

In [ ]:
# converting the weapon_name col to upercase
weapon_gloss["weapon_name"] = weapon_gloss["weapon_name"].str.upper()
weapon_gloss.head(10)